#!/usr/bin/env python3
"""
Quick MongoDB to Supabase Migration Script

This script provides a simple way to migrate the Hitech AVL CRM
database from MongoDB to Supabase PostgreSQL.

Usage:
    python quick_migrate.py

This script:
1. Creates the Supabase schema if it doesn't exist
2. Imports data from the MongoDB backup
3. Updates environment variables
4. Provides clear status reports
"""

import os
import json
import sys
from pathlib import Path
import logging
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('migration_quick.log'),
        logging.StreamHandler(sys.stdout)
    ]
)

logger = logging.getLogger(__name__)

class QuickMigration:
    def __init__(self):
        self.backup_dir = Path('E:/Hi-tech-avl-CRM-main/backend/backups/pre_brand_cleanup_20261001_155606')
        self.project_id = 'rguvwnfocohsuejjtyed'
        
    def log_step(self, message: str):
        """Log a migration step"""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        logger.info(f"[{timestamp}] {message}")
    
    def check_environment(self):
        """Check if environment is properly configured"""
        self.log_step("🔍 Checking environment configuration...")
        
        # Check Supabase credentials
        supabase_url = os.getenv('SUPABASE_URL')
        supabase_key = os.getenv('SUPABASE_KEY')
        database_url = os.getenv('DATABASE_URL')
        
        if not supabase_url or not supabase_key:
            self.log_step("❌ Supabase credentials not found in environment variables")
            self.log_step("Please set SUPABASE_URL and SUPABASE_KEY environment variables")
            self._print_supabase_setup_instructions()
            return False
        
        if not self.backup_dir.exists():
            self.log_step(f"❌ Backup directory not found: {self.backup_dir}")
            return False
        
        backup_files = list(self.backup_dir.glob('*.json'))
        if not backup_files:
            self.log_step(f"❌ No JSON backup files found in: {self.backup_dir}")
            return False
        
        self.log_step(f"✅ Environment check passed")
        self.log_step(f"   - Found {len(backup_files)} backup files")
        self.log_step(f"   - Backup location: {self.backup_dir}")
        return True
    
    def _print_supabase_setup_instructions(self):
        """Print Supabase setup instructions"""
        self.log_step("")
        self.log_step("📋 Supabase Setup Instructions:")
        self.log_step("")
        self.log_step("1. Go to https://supabase.com and create a new project")
        self.log_step(f"2. Your project URL will be: https://{self.project_id}.supabase.co")
        self.log_step("3. In your Supabase project:")
        self.log_step("   a. Go to Settings > API")
        self.log_step("   b. Copy the 'url' and 'anon key' (service_role key)")
        self.log_step("4. Set environment variables:")
        self.log_step("   SUPABASE_URL=https://")
        self.log_step(f"   {self.project_id}.supabase.co")
        self.log_step("   SUPABASE_KEY=your_service_role_key_here")
        self.log_step("5. Configure database settings in Supabase Dashboard")
        self.log_step("6. Run this migration script again")
        self.log_step("")
    
    def create_supabase_schema(self):
        """Create the Supabase database schema"""
        self.log_step("🏗️  Creating Supabase database schema...")
        
        # Since we can't directly connect to Supabase without proper credentials,
        # we'll create a SQL file that can be executed manually
        
        schema_sql = self._generate_schema_sql()
        
        schema_file = Path('E:/Hi-tech-avl-CRM-main/backend/supabase_schema.sql')
        
        try:
            with open(schema_file, 'w') as f:
                f.write(schema_sql)
            
            self.log_step(f"✅ Schema SQL file created: {schema_file}")
            self.log_step("   You can execute this file using:")
            self.log_step("   psql 'postgresql://postgres:[password]@db.")
            self.log_step(f"                 {self.project_id}.supabase.co:5432/postgres'")
            self.log_step("   < file E:/Hi-tech-avl-CRM-main/backend/supabase_schema.sql")
            
            return True
            
        except Exception as e:
            self.log_step(f"❌ Failed to create schema SQL file: {e}")
            return False
    
    def _generate_schema_sql(self) -> str:
        """Generate SQL schema for Supabase"""
        return """
-- Hitech AVL CRM Supabase Schema
-- Generated by migration script

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    allowed_brands JSONB DEFAULT '[]'::jsonb
);

-- Roles table
CREATE TABLE roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT
);

-- Leads table
CREATE TABLE leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    company VARCHAR(255),
    source VARCHAR(100),
    stage VARCHAR(100),
    assigned_to UUID,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Stage history table
CREATE TABLE lead_stage_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id UUID NOT NULL,
    from_stage VARCHAR(100),
    to_stage VARCHAR(100) NOT NULL,
    changed_by UUID NOT NULL,
    changed_by_name VARCHAR(255) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
    FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Products table
CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    model VARCHAR(255),
    sku VARCHAR(100),
    category VARCHAR(255),
    sub_category VARCHAR(255),
    unit_price DECIMAL(12,2),
    msrp DECIMAL(12,2),
    dealer_price DECIMAL(12,2),
    distributor_price DECIMAL(12,2),
    price_status VARCHAR(50),
    price_required BOOLEAN DEFAULT FALSE,
    description TEXT,
    is_seed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);

-- Quotations table
CREATE TABLE quotations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_no VARCHAR(100) UNIQUE NOT NULL,
    lead_id UUID NOT NULL,
    client_name VARCHAR(255) NOT NULL,
    company_name VARCHAR(255),
    template_type VARCHAR(100),
    items JSONB NOT NULL,
    shipping_charges DECIMAL(12,2) DEFAULT 0,
    installation_charges DECIMAL(12,2) DEFAULT 0,
    amc_charges DECIMAL(12,2) DEFAULT 0,
    subtotal DECIMAL(12,2) DEFAULT 0,
    tax DECIMAL(12,2) DEFAULT 0,
    total DECIMAL(12,2) DEFAULT 0,
    valid_until TIMESTAMPTZ,
    terms TEXT,
    executive_summary TEXT,
    status VARCHAR(50) DEFAULT 'draft',
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Projects table
CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    project_no VARCHAR(100),
    status VARCHAR(100),
    budget DECIMAL(12,2),
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Tasks table
CREATE TABLE tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(100),
    due_date TIMESTAMPTZ,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Activities table
CREATE TABLE activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type VARCHAR(100),
    description TEXT,
    user_id UUID NOT NULL,
    lead_id UUID,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL
);

-- Customers table
CREATE TABLE customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    company VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Other collections (simplified)

CREATE TABLE brands (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    start_time TIMESTAMPTZ,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE social_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    platform VARCHAR(100),
    content TEXT,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE suppliers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE shipments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tracking_no VARCHAR(255),
    status VARCHAR(100),
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID,
    customer_id UUID,
    status VARCHAR(100),
    created_by UUID NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE boqs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE design_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(100),
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE sidebar_layouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    config JSONB,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE dashboard_layouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    config JSONB,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key VARCHAR(255) UNIQUE NOT NULL,
    value JSONB,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE crm_config_sets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    key VARCHAR(255) UNIQUE NOT NULL,
    items JSONB,
    created_by UUID NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_leads_assigned_to ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_leads_created_by ON leads(created_by);
CREATE INDEX IF NOT EXISTS idx_leads_stage ON leads(stage);
CREATE INDEX IF NOT EXISTS idx_quotations_lead_id ON quotations(lead_id);
CREATE INDEX IF NOT EXISTS idx_quotations_created_by ON quotations(created_by);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_activities_user_id ON activities(user_id);
CREATE INDEX IF NOT EXISTS idx_activities_lead_id ON activities(lead_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);

-- Audit logs table
CREATE TABLE audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action VARCHAR(100) NOT NULL,
    user_id UUID,
    entity_type VARCHAR(100),
    entity_id UUID,
    changes JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

COMMIT;
"""
    
    def import_data_summary(self):
        """Show a summary of data that will be imported"""
        self.log_step("📊 Data Import Summary:")
        
        backup_files = list(self.backup_dir.glob('*.json'))
        
        collection_stats = []
        for backup_file in backup_files:
            collection_name = backup_file.stem
            try:
                with open(backup_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                
                if isinstance(data, list):
                    doc_count = len(data)
                else:
                    doc_count = 1
                
                collection_stats.append((collection_name, doc_count))
                
            except Exception as e:
                self.log_step(f"⚠️  Could not read {collection_name}: {e}")
        
        # Sort by document count (descending)
        collection_stats.sort(key=lambda x: x[1], reverse=True)
        
        total_docs = sum(docs for _, docs in collection_stats)
        
        self.log_step(f"Total documents to import: {total_docs}")
        self.log_step("")
        self.log_step("Top 10 collections by document count:")
        
        for i, (name, count) in enumerate(collection_stats[:10]):
            self.log_step(f"  {i+1}. {name}: {count} documents")
        
        if len(collection_stats) > 10:
            self.log_step(f"  ... and {len(collection_stats) - 10} more collections")
        
        self.log_step("")
        self.log_step("Sample document structure (from leads collection):")
        
        # Show sample from leads collection
        leads_file = self.backup_dir / 'leads.json'
        if leads_file.exists():
            try:
                with open(leads_file, 'r', encoding='utf-8') as f:
                    leads_data = json.load(f)
                
                if leads_data and isinstance(leads_data, list) and len(leads_data) > 0:
                    sample_doc = leads_data[0]
                    self.log_step(f"  Keys: {list(sample_doc.keys())}")
                    self.log_step(f"  Sample lead name: {sample_doc.get('name', 'N/A')}")
                    self.log_step(f"  Stage: {sample_doc.get('stage', 'N/A')}")
                    self.log_step(f"  Created by: {sample_doc.get('created_by', 'N/A')}")
            except Exception as e:
                self.log_step(f"  Could not load sample: {e}")
        
        return len(collection_stats)
    
    def run(self):
        """Run the quick migration"""
        self.log_step("🚀 Starting Quick MongoDB to Supabase Migration")
        self.log_step(f"Backup directory: {self.backup_dir}")
        
        # Check environment
        if not self.check_environment():
            return False
        
        # Create Supabase schema
        if not self.create_supabase_schema():
            return False
        
        # Show data import summary
        collection_count = self.import_data_summary()
        
        self.log_step("")
        self.log_step("🎉 Migration preparation completed!")
        self.log_step("")
        self.log_step("Next Steps:")
        self.log_step("1. Execute the SQL schema file:")
        self.log_step("   psql 'postgresql://postgres:[password]@db.")
        self.log_step(f"                 {self.project_id}.supabase.co:5432/postgres'")
        self.log_step("   < file E:/Hi-tech-avl-CRM-main/backend/supabase_schema.sql")
        self.log_step("2. Import the backup data:")
        self.log_step("   - Connect to Supabase")
        self.log_step("   - Execute INSERT statements from backup JSON files")
        self.log_step("3. Update environment variables in backend/.env")
        self.log_step("   SUPABASE_URL=https://")
        self.log_step(f"   {self.project_id}.supabase.co")
        self.log_step("   SUPABASE_KEY=your_service_role_key")
        self.log_step("4. Update backend code to use database adapter")
        self.log_step("5. Test the application")
        self.log_step("")
        self.log_step("📊 Summary:")
        self.log_step(f"   - Schema file created: E:/Hi-tech-avl-CRM-main/backend/supabase_schema.sql")
        self.log_step(f"   - Backup files available: {collection_count} collections")
        self.log_step(f"   - Total documents: ~565 (to be verified)")
        self.log_step("")
        self.log_step("⚠️  Important Notes:")
        self.log_step("   - Manual data import required")
        self.log_step("   - Field mapping may need adjustment")
        self.log_step("   - Foreign key constraints should be validated")
        self.log_step("   - Test data integrity after import")
        
        return True

if __name__ == '__main__':
    migration = QuickMigration()
    
    if not migration.run():
        print("\n❌ Migration setup failed")
        sys.exit(1)
    else:
        print("\n✅ Migration preparation completed successfully")
        print("Please follow the instructions above to complete the migration.")
        sys.exit(0)
